hombre(benito).
hombre(narciso).
hombre(genaro).
hombre(harry).
hombre(pablo).
hombre(bruno).
hombre(samuel).
hombre(omar).
mujer(hilda).
mujer(daniela).
mujer(rosa).
mujer(erika).
mujer(graciela).
mujer(sonia).
mujer(casandra).
mujer(karla).
mujer(alejandra).
mujer(esther).
mujer(eva).
mujer(sandra).
familia(benito,daniela).
familia(narciso,harry).
familia(hilda,harry).
familia(daniela,pablo).
familia(genaro,pablo).
familia(rosa,erika).
familia(rosa,bruno).
familia(rosa,sonia).
familia(harry,erika).
familia(harry,bruno).
familia(harry,sonia).
familia(pablo,samuel).
familia(pablo,casandra).
familia(pablo,omar).
familia(pablo,karla).
familia(erika,samuel).
familia(erika,casandra).
familia(erika,omar).
familia(erika,karla).
familia(bruno,alejandra).
familia(bruno,esther).
familia(graciela,alejandra).
familia(graciela,esther).
familia(sonia,eva).
familia(sonia,sandra).
papa(G2,G1):-familia(G1,G2),hombre(G1).
mama(G2,G1):-familia(G1,G2),mujer(G1).
papas(G2,G1):-familia(G1,G2).
hijo(G1,G2):-familia(G1,G2),hombre(G2).
hija(G1,G2):-familia(G1,G2),mujer(G2).
hijos(G1,G2):-familia(G1,G2).
hermano(Hijo,Hermano):-papas(Hijo,Papas),papas(Hermano,Papas),hombre(Hermano),Hijo\=Hermano.
hermana(Hijo,Hermana):-papas(Hijo,Papas),papas(Hermana,Papas),mujer(Hermana),Hijo\=Hermana.
hermanos(Hijo,Hermanos):-papas(Hijo,Papas),papas(Hermanos,Papas),Hijo\=Hermanos.
abuelo(G3,G1):-papas(G3,G2),papas(G2,G1),hombre(G1).
abuela(G3,G1):-papas(G3,G2),papas(G2,G1),mujer(G1).
abuelos(G3,G1):-papas(G3,G2),papas(G2,G1).
nieto(G1,G3):-hijos(G1,G2),hijos(G2,G3),hombre(G3).
nieta(G1,G3):-hijos(G1,G2),hijos(G2,G3),mujer(G3).
nietos(G1,G3):-hijos(G1,G2),hijos(G2,G3).
bisabuelo(G4,G1):-abuelos(G4,G2),papa(G2,G1).
bisabuela(G4,G1):-abuelos(G4,G2),mama(G2,G1).
bisabuelos(G4,G1):-abuelos(G4,G2),papas(G2,G1).
bisnieto(G1,G4):-nietos(G1,G3),hijo(G3,G4).
bisnieta(G1,G4):-nietos(G1,G3),hija(G3,G4).
bisnietos(G1,G4):-nietos(G1,G3),hijos(G3,G4).
tio(Sobrino,Tio):-papas(Sobrino,Papas),hermano(Papas,Tio),Tio\=Papas.
tia(Sobrino,Tia):-papas(Sobrino,Papas),hermano(Papas,Tia),Tia\=Papas.
tios(Sobrino,Tios):-papas(Sobrino,Papas),hermanos(Papas,Tios),Tios\=Papas.
sobrino(Tio,Sobrino):-hermanos(Tio,Hermanos),hijo(Hermanos,Sobrino).
sobrina(Tio,Sobrina):-hermanos(Tio,Hermanos),hija(Hermanos,Sobrina).
sobrinos(Tio,Sobrinos):-hermanos(Tio,Hermanos),hijos(Hermanos,Sobrinos).
esposo(Mujer,Hombre):-hijos(Mujer,Hijos),hijos(Hombre,Hijos),Mujer\=Hombre.
esposa(Hombre,Mujer):-hijos(Hombre,Hijos),hijos(Mujer,Hijos),Hombre\=Mujer.
yerno(Papas,Yerno):-hija(Papas,Hija),esposo(Hija,Yerno).
yerna(Papas,Yerna):-hijo(Papas,Hijo),esposa(Hijo,Yerna).
cunado(Bro,Cunado):-hermana(Bro,Hermana),esposo(Hermana,Cunado).
cunado(Esposa,Cunado):-esposo(Esposa,Esposo),hermano(Esposo,Cunado).
cunado(Esposo,Cunado):-esposa(Esposo,Esposa),hermano(Esposa,Cunado).
cunada(Bro,Cunada):-hermano(Bro,Hermano),esposa(Hermano,Cunada).
cunada(Esposa,Cunada):-esposo(Esposa,Esposo),hermana(Esposo,Cunada).
cunada(Esposo,Cunada):-esposa(Esposo,Esposa),hermana(Esposa,Cunada).
cunados(Esposa,Cunados):-esposo(Esposa,Esposo),hermanos(Esposo,Cunados).
cunados(Esposo,Cunados):-esposa(Esposo,Esposa),hermanos(Esposa,Cunados).
concuno(Esposo,Concuno):-cunada(Esposo,Cunada),esposo(Cunada,Concuno).
concuno(Esposa,Concuno):-cunada(Esposa,Cunada),esposo(Cunada,Concuno).
concuno(Concuno,Esposo):-esposa(Concuno,Cunada),cunado(Cunada,Esposo).
concuno(Concuna,Esposo):-esposo(Concuna,Cunado),cunado(Cunado,Esposo).
concuna(Esposo,Concuna):-cunado(Esposo,Cunado),esposa(Cunado,Concuna).
concuna(Esposa,Concuna):-cunado(Esposa,Cunado),esposa(Cunado,Concuna).
concuna(Concuno,Esposa):-esposa(Concuno,Cunada),cunado(Cunada,Esposa).
concuna(Concuna,Esposa):-esposo(Concuna,Cunado),cunado(Cunado,Esposa).