hombre(benito).
hombre(narciso).
hombre(genaro).
hombre(harry).
hombre(pablo).
hombre(bruno).
hombre(samuel).
hombre(omar).
mujer(hilda).
mujer(daniela).
mujer(rosa).
mujer(erika).
mujer(graciela).
mujer(sonia).
mujer(casandra).
mujer(karla).
mujer(alejandra).
mujer(esther).
mujer(eva).
mujer(sandra).
familia(benito,daniela).
familia(narciso,harry).
familia(hilda,harry).
familia(daniela,pablo).
familia(genaro,pablo).
familia(rosa,erika).
familia(rosa,bruno).
familia(rosa,sonia).
familia(harry,erika).
familia(harry,bruno).
familia(harry,sonia).
familia(pablo,samuel).
familia(pablo,casandra).
familia(pablo,omar).
familia(pablo,karla).
familia(erika,samuel).
familia(erika,casandra).
familia(erika,omar).
familia(erika,karla).
familia(bruno,alejandra).
familia(bruno,esther).
familia(graciela,alejandra).
familia(graciela,esther).
familia(sonia,eva).
familia(sonia,sandra).

